### ISSUE TITLE
Displays wrong icon

### ISSUE THREAD

**Issue by AlphaLeoli** [FuncFusion/mc-dp-icons#16]
im making a datapack and when i have 'game' as one of the folders in the function folder, it shows as an enderchest.
![image](https://github.com/user-attachments/assets/9225e255-ab6d-4994-bdec-3d81c3ede89a)

**Comment by amqndin** [comment]
hey! i am responsible for this logic. you see, this is not a bug, its just a flaw due to limitations in creating icon themes for vscode. simply put, assigning a special icon to namespaces is not something you should be able to do in an icon theme, and it is done via a workaround. an icon is only tied to a file / folder by a specific name, you cant specify any more than that, so if you have atleast one namespace called `game` that means any folder that is also named `game` will have the enderchest icon. 

though, if its really frustrating you, you could either change the name of one of the folders, or go to extensions options and disable namespace icons.

**Comment by AlphaLeoli** [comment]
is it possible to add an override with like a right click menu or smt ?

**Comment by amqndin** [comment]
As i've already said earlier, an icon is only tied to a file / folder by a specific name, you *cant specify any more than that*, so if you have atleast one namespace called `game` that means **any** folder that is also named `game` will have the enderchest icon. So the answer is no.
